title: Institute of Transportation Engineers @ UC Berkeley
short_title: ITE at Berkeley
description: We are the student chapter of the Institute of Transportation Engineers at the University of California, Berkeley. We provide opportunities for interested students to connect with transportation professionals in both public and private sectors.
url: "https://ite.studentorg.berkeley.edu"
baseurl: ""
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
