---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Redirects
  create: documents
  match: "*"
  new_doc_ext: md
  templates:
  - redirect
- type: heading
  label: Content
- type: document
  path: index.md
  label: Home
- type: document
  path: about.md
  label: About
- type: document
  path: team.md
  label: Our Team
- type: document
  path: join.md
  label: Join
  match: "**/*"
- type: directory
  path: _data
  label: Sponsors, Contact Info, Other Variables
  create: none
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
