name: Jekyll Deploy

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses: lemonarc/jekyll-action@1.0.0

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: deploy # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
        
    - uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd public_html && git clone --single-branch --branch deploy https://github.com/Transpo-Berkeley/transpo-berkeley.github.io.git
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
