name: Jekyll Deploy

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses:  lemonarc/jekyll-action@1.0.0
  
    - uses: hengkx/ssh-deploy@v1.0.1
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: '/github/workspace/_site'
        TARGET: ${{ secrets.DEPLOY_DEST_PATH }}
        AFTER_COMMAND: 'npm run stop && npm install --production && npm run start'
